#!/bin/bash
#CODE BY D1MMY
pkg install php
pkg install python
pkg install wget
pkg install fish
fish
pip install lolcat
sleep 2
pip install lolcat
clear
echo "
 ██▓███   ▒█████   █     █░▓█████  ██▀███       
▓██░  ██▒▒██▒  ██▒▓█░ █ ░█░▓█   ▀ ▓██ ▒ ██▒     
▓██░ ██▓▒▒██░  ██▒▒█░ █ ░█ ▒███   ▓██ ░▄█ ▒     
▒██▄█▓▒ ▒▒██   ██░░█░ █ ░█ ▒▓█  ▄ ▒██▀▀█▄       
▒██▒ ░  ░░ ████▓▒░░░██▒██▓ ░▒████▒░██▓ ▒██▒     
▒▓▒░ ░  ░░ ▒░▒░▒░ ░ ▓░▒ ▒  ░░ ▒░ ░░ ▒▓ ░▒▓░     
░▒ ░       ░ ▒ ▒░   ▒ ░ ░   ░ ░  ░  ░▒ ░ ▒░     
░░       ░ ░ ░ ▒    ░   ░     ░     ░░   ░      
             ░ ░      ░       ░  ░   ░          
                                                
 ██▀███  ▓█████ ██▒   █▓ ▒█████   ██▓  ▄▄▄█████▓
▓██ ▒ ██▒▓█   ▀▓██░   █▒▒██▒  ██▒▓██▒  ▓  ██▒ ▓▒
▓██ ░▄█ ▒▒███   ▓██  █▒░▒██░  ██▒▒██░  ▒ ▓██░ ▒░
▒██▀▀█▄  ▒▓█  ▄  ▒██ █░░▒██   ██░▒██░  ░ ▓██▓ ░ 
░██▓ ▒██▒░▒████▒  ▒▀█░  ░ ████▓▒░░██████▒▒██▒ ░ 
░ ▒▓ ░▒▓░░░ ▒░ ░  ░ ▐░  ░ ▒░▒░▒░ ░ ▒░▓  ░▒ ░░   
  ░▒ ░ ▒░ ░ ░  ░  ░ ░░    ░ ▒ ▒░ ░ ░ ▒  ░  ░    
  ░░   ░    ░       ░░  ░ ░ ░ ▒    ░ ░   ░      
   ░        ░  ░     ░      ░ ░      ░  ░       
                    ░                           
▄▄▄█████▓ ▒█████   ▒█████   ██▓                 
▓  ██▒ ▓▒▒██▒  ██▒▒██▒  ██▒▓██▒                 
▒ ▓██░ ▒░▒██░  ██▒▒██░  ██▒▒██░                 
░ ▓██▓ ░ ▒██   ██░▒██   ██░▒██░                 
  ▒██▒ ░ ░ ████▓▒░░ ████▓▒░░██████▒             
  ▒ ░░   ░ ▒░▒░▒░ ░ ▒░▒░▒░ ░ ▒░▓  ░             
    ░      ░ ▒ ▒░   ░ ▒ ▒░ ░ ░ ▒  ░             
  ░      ░ ░ ░ ▒  ░ ░ ░ ▒    ░ ░                
             ░ ░      ░ ░      ░  ░             
                                                
" | lolcat
sleep 2
unzip  pro.zip
rm -rf pro.zip
clear
chmod +x *
sleep 1
clear
cd ~
cd cardon/pro/core/lib/xdg-open
chmod +x *
clear
echo " YOU CAN OPRATE THE TOOL TYPE " | lolcat
echo "            		bash carder.sh " | lolcat
echo ""
echo "       HAPPY   HACKING             " | lolcat
sleep 4
fi











